<br>
<br>
<div class="container-fluid"> 
    <div class="col-md-8 col-md-offset-2">
    <h3>1. Introduction</h3>
    <p class="lead text-justify">
    With the rapid advances in high-throughput sequencing technologies, thousands of extrachromosomal circular DNA (eccDNAs) from human genome have been reported by computational analysis of these sequencing data. But loss-of-function experiments are difficult to carry out due to the overlap between circular and linear chromosomes in most eccDNAs, making it challenging to directly interpret their molecular functions.
    Studies have indicated that eccDNA could be an enormous potential biomarker for diagnosis and prognosis of cancer, making the research on eccDNA to be a hotspot. However, as the increasing number of human eccDNAs generated by computational analysis of sequencing data, it is a big challenge for researchers to gather all the current available data of eccDNA to better understand eccDNA’s roles in different cell types.
    </p>
    <p class="lead text-justify">Herein, we present CircleBase, an integrated resource and analysis platform for curating and interpreting eccDNAs in different cell types. CircleBase identifies putative functional eccDNAs by incorporating high-throughput experimental datasets, computational predictions and manual annotations, which are classified into six annotation sections including “targeting genes”, “epigenetic regulation”, “regulatory elements”, “chromatin accessibility” and “chromatin interaction” and “genetic variants”. With state-of-the-art methods, CircleBase establishes eccDNA-target and regulator-eccDNA regulatory networks, which are displayed by informative visualization tools and ranked by a scoring system to prioritize eccDNAs, targets and regulators.
    </p>
    <br>
    <hr style="border:2px solid black">
    <br>
    
    <h3>2. Web interface of CircleBase</h3>
    <h4>2.1 How to search CircleBase?</h4>
    <p class="alert alert-info">
    Users can search eccDNA through two ways including 'quick Search' and 'batch Search' as shown below.
    </p>
    <img src="assets/img/quick-search.png" class="img-responsive img-thumbnail" alt="search-quick.png">
    <img src="assets/img/batch-search.png" class="img-responsive img-thumbnail" alt="search-batch.png">
    
    <h4>2.2 Search Result</h4>
    <p class="alert alert-info">Search resul including 'primary' and 'detail' sections as shown below.</p> 
    <img src="assets/img/basic-result.png" class="img-responsive img-thumbnail" alt="search-result.png">
    <img src="assets/img/detail-1.png" class="img-responsive img-thumbnail" alt="detail.png">
    <img src="assets/img/detail-2.png" class="img-responsive img-thumbnail" alt="detail.png">
    <img src="assets/img/detail-3.png" class="img-responsive img-thumbnail" alt="detail.png">
    <img src="assets/img/detail-4.png" class="img-responsive img-thumbnail" alt="detail.png">
    <img src="assets/img/detail-5.png" class="img-responsive img-thumbnail" alt="detail.png">
    <img src="assets/img/detail-6.png" class="img-responsive img-thumbnail" alt="detail.png">
    <img src="assets/img/detail-7.png" class="img-responsive img-thumbnail" alt="detail.png">
    <img src="assets/img/detail-8.png" class="img-responsive img-thumbnail" alt="detail.png">
    
    </div>
</div>
