<div id="banner" style="padding-top:40px;padding-bottom:40px;margin-top:-10px; background-image: url(assets/img/background-1.jpg);background-repeat: no-repeat;background-size:cover;">
<div class="container-fluid">
<div class="col-md-10 col-md-offset-1">
<p id="slogan" style="font-size:35px;color:rgb(216,164,6); margin-left:40px">CircleBase: an integrated resource and analysis platform for human eccDNAs 
</p>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</div>
</div>
</div>

<div class="container-fluid">
	<br>
	<br>
	<div class="col-md-8 col-md-offset-1">
		<form class="form" role="form" class="quick" action="<?php echo site_url('search/quick')?>" method="POST">
            <div class="form-group col-xs-4 col-sm-4 col-md-2">
                <select class="form-control" id="assembly" name="assembly">
                <option value="hg19">hg19</option>
                <option value="hg38">hg38</option>
                </select>
            </div>
			<div class="form-group col-xs-8 col-sm-8 col-md-10">
				<div class="input-group">
				<input class="form-control" id="item" name="item" type="text" placeholder="gene symbol, genomic region, eccDNA_id" >
				<span class="input-group-btn"> <button class="btn btn-danger" type="submit" title="Click to search"> <span class="glyphicon glyphicon-search" aria-hidden="true"></span> </button> </span> 
				</div> 
				examples&nbsp;:&nbsp;
				<a href="javascript:void(0);" class="tip">EGFR</a> &nbsp;/&nbsp;
				<a href="javascript:void(0);" class="tip">MYC</a> &nbsp;/&nbsp;
                <a href="javascript:void(0);" class="tip">chr7-52165741-53138302</a> &nbsp;/&nbsp;
				<a href="javascript:void(0);" class="tip">ecc600533</a>
			</div>
		</form>
		<br>
		<br>
		<br>
		<!--<p class="alert alert-warning">Note: CircleBase and its resources are freely available for academic usage. For some of the resources, licenses are required for non-academic usage, please contact the original content provider for that purpose.<a id="disclaimer-modal-link" data-target='#disclaimer-modal' data-toggle='modal' href='javascript:void(0);'>View Disclaimer</a></p>-->
		<h2>Welcome to CircleBase</h2>
		<hr style="border: 2px solid black; --darkreader-inline-border-top:#8c8273; --darkreader-inline-border-right:#8c8273; --darkreader-inline-border-bottom:#8c8273; --darkreader-inline-border-left:#8c8273;" data-darkreader-inline-border-top="" data-darkreader-inline-border-right="" data-darkreader-inline-border-bottom="" data-darkreader-inline-border-left="">
		<p class="lead text-justify">
		Here, we have developed a novel database, CircleBase, to provide interpretation of extrachromosomal circular DNAs (eccDNAs) which have been reported by computational analysis of sequencing data. CircleBase identifies putative functional eccDNAs by incorporating high-throughput experimental datasets from ENCODE and other sources, computational predictions and manual annotations. Briefly, CircleBase classifies the genomic and epigenomic data into six annotation sections, including 'targeting genes', 'epigenetic regulations', 'regulatory elements', 'chromatin accessibility', 'chromatin interactions', and 'genetic variants'. These data sources are combined into a powerful system to score eccDNAs and help interpreting the potential functions of eccDNA in the human genome. CircleBase provides a user-friendly interface for browsing, searching and downloading eccDNAs in various cell/tissue types. This platform will facilitate the identification of functional eccDNAs and help researchers to investigate the regulation networks between eccDNAs and genetic/epigenetic factors. We are dedicated to maintaining CircleBase and extending the range of organisms and cell types to keep the resource updated.
		</p>
		<h2>Workflow of CircleBase</h2>
		<hr style="border:2px solid black">
		<img src="assets/img/workflow.jpg" class="img-responsive" alt="pipeline">
		<h2>Motivation of CircleBase</h2>
		<hr style="border:2px solid black">
		<p class="lead text-justify">
		Extrachromosomal circular DNA (eccDNA) originates from chromosomal DNA but is independent of it. EccDNA is ubiquitous in various eukaryotes and plays multiple biological roles in different cell types. Researchers have known for decades that eccDNA occurs in tumor cells. However, comprehensive studies on their structure and function have returned relatively little useful information because of the limitations of available detection and analysis technology. Other researchers have exploited recently developed high-throughput sequencing technology and eccDNA identification methods, revealing strong associations between eccDNA and cancers. It indicates that eccDNAs are promising biomarkers for cancer diagnosis and prognosis and are, therefore, research hotspots. However, the number of human eccDNAs generated by the computational analysis of sequencing data has increased. Therefore, it has been challenging for researchers to compile available data to investigate their functions. In fact, the biological functions of most eccDNAs remain unknown and loss-of-function experiments are difficult to perform, as circular and linear chromosomes overlap in most cases. Moreover, the formation and regulation of most eccDNAs remain unclear and their targeting genes, genetic variants, and chromatin characteristics in various cell types have seldom been explored. Therefore, an integrated database and analysis platform is required for human eccDNAs. Herein, we build up an important analysis platform for exploring the biological function of eccDNA in the human genome and its application in cancer diagnosis and treatment.
		</p>
		<br>
		<!--<h2>Publication detail</h2>
		<hr style="border:2px solid black">
		<p><a href="https://academic.oup.com/nar/article/4588107" target="_blank" class="not-new-window">CircleBase: an integrated genetic and clinical database for coding variants in the human genome.</a> 2018. Nucleic Acids Research.</p>
		<br><br>-->
	</div>

	<div class="col-md-2">
	<p class="panel-title">Recent Updates</p>
    
    <div class="panel panel-default">
	<div class="panel-body">
	<p><span style="color:red" class="glyphicon glyphicon-flag"></span><strong>[3/8/2021]</strong>
		Finish scoring system for eccDNA prioritization and diffusion system to prioritize target genes.
	</p>
	</div>
	</div>
    
    <div class="panel panel-default">
	<div class="panel-body">
	<p><strong>[26/7/2021]</strong>
		The high-resolution chromatin interactions, clusters of transcription factor binding, somatic mutations, enhancers or super-enhancers and their predicted targets were illustrated in a circular ideogram layout by BioCircos.
	</p>
	</div>
	</div>
    
    <div class="panel panel-default">
	<div class="panel-body">
	<p><strong>[6/7/2021]</strong>
		Function enrichment analyses was performed using the R package clusterProfiler version 4.0.2.
	</p>
	</div>
	</div>
    
    <div class="panel panel-default">
	<div class="panel-body">
	<p><strong>[26/6/2021]</strong>
		Regulatory networks were constructed by combining enhancer-gene pairs from three sections including “Targeting genes”, “Regulatory elements” and “Chromatin interactions”. 
	</p>
	</div>
	</div>
	
	<div class="panel panel-default">
	<div class="panel-body">
	<p><strong>[12/6/2021]</strong>
		Development of query system done.
	</p>
	</div>
	</div>
	
	<div class="panel panel-default">
	<div class="panel-body">
	<p><strong>[22/4/2021]</strong>
		Associate data from multiple sources and deposit it into the MySQL.
	</p>
	</div>
	</div>
	
	<div class="panel panel-default">
	<div class="panel-body">
	<p><strong>[2/11/2020]</strong>
		Data cleaning were done.
	</p>
	</div>
	</div>
	
	<div class="panel panel-default">
	<div class="panel-body">
	<p><strong>[27/9/2020]</strong>
		Retrieved data from multiple sources such as GEO, GSA, ENCODE, etc.
	</p>
	</div>
	</div>

	<div class="panel panel-default">
	<div class="panel-body">
	<p><strong>[5/1/2020]</strong>
		Website environment configuration, design and analysis method confirmation.
	</p>
	</div>
	</div>
	
	</div>
</div>
